export default {
  dev: {
    AUTH: 'https://open-dev.shiguangkey.com/api',
    EXAM: 'https://exam-dev.shiguangkey.com/api',
    STUDY: 'https://www-dev.shiguangkey.com/api',
    MAIN: 'https://www-dev.shiguangkey.com',
    MOCK: 'http://127.0.0.1:9999/api',
    CORS: [
      'https://auth2-dev.shiguangkey.com',
      'https://www-dev.shiguangkey.com',
      'https://exam-dev.shiguangkey.com',
    ],
    CRM: 'https://crm-dev.shiguangkey.com',
    WORK_PREFIX: 'https://work-dev.shiguangkey.com',
    LOGIN: 'https://iwork-dev.shiguangkey.com',
    TEACHER: 'https://teacher-dev.shiguangkey.com',
    IM: 'https://im-test.shiguangkey.com',
  },
  local: {
    AUTH: 'https://open-test.shiguangkey.com/api',
    STUDY: 'https://www-test.shiguangkey.com/api',
    EXAM: 'https://exam-test.shiguangkey.com/api',
    MAIN: 'https://www-test.shiguangkey.com',
    CORS: [
      'https://auth2-test.shiguangkey.com',
      'https://www-test.shiguangkey.com',
      'https://exam-test.shiguangkey.com',
    ],
    CRM: 'https://crm-test.shiguangkey.com',
    WORK_PREFIX: 'https://work-test.shiguangkey.com',
    LOGIN: 'https://iwork-test.shiguangkey.com',
    TEACHER: 'https://teacher-test.shiguangkey.com',
    IM: 'https://im-test.shiguangkey.com',
  },
  pre: {
    AUTH: 'https://open-pre.shiguangkey.com/api',
    STUDY: 'https://www-pre.shiguangkey.com/api',
    EXAM: 'https://exam-pre.shiguangkey.com/api',
    MAIN: 'https://www-pre.shiguangkey.com',
    CORS: [
      'https://auth2-pre.shiguangkey.com',
      'https://www-pre.shiguangkey.com',
      'https://exam-pre.shiguangkey.com',
    ],
    CRM: 'https://crm-pre.shiguangkey.com',
    WORK_PREFIX: 'https://work-pre.shiguangkey.com',
    LOGIN: 'https://iwork-pre.shiguangkey.com',
    TEACHER: 'https://teacher-pre.shiguangkey.com',
    IM: 'https://im-test.shiguangkey.com',
  },
  prod: {
    AUTH: 'https://open.shiguangkey.com/api',
    STUDY: 'https://www.shiguangkey.com/api',
    EXAM: 'https://exam.shiguangkey.com/api',
    MAIN: 'https://www.shiguangkey.com',
    CORS: [
      'https://auth2.shiguangkey.com',
      'https://www.shiguangkey.com',
      'https://exam.shiguangkey.com',
    ],
    CRM: 'https://crm.shiguangkey.com',
    WORK_PREFIX: 'https://work.shiguangkey.com',
    LOGIN: 'https://iwork.shiguangkey.com',
    TEACHER: 'https://teacher.shiguangkey.com',
    IM: 'https://im.shiguangkey.com',
  },
};
